### ISSUE TITLE
can't generate whatsapp session with error message "could not decode binary:invalid string with tag 174"

### ISSUE THREAD

**Issue by muhsatrio** [k1m0ch1/WhatsappLogin#1]
Hi @k1m0ch1, I want to start contribute on NeMo repository, as the first step I try to generate whatsapp session in this repository, so I followed the guideline to generate the session. But, I got this error message when I scan with WhatsApp Scan QR
<img width="954" alt="Screen Shot 2021-10-01 at 06 17 26" src="https://user-images.githubusercontent.com/11547086/135542239-da77fef7-a4c3-4cc0-b027-d69ac4e935fa.png">

I try again with prefix `08xxxxxxx`, but got the same error too

<img width="1434" alt="Screen Shot 2021-10-01 at 06 15 34" src="https://user-images.githubusercontent.com/11547086/135542280-bafd160b-e2ba-4212-9ab0-53c608808fa5.png">

Is there any guide for this? thank you and stay safe!

**Comment by k1m0ch1** [comment]
you should check the file within the directory, it suppose to be generate a *.gob` file, and if that file is existed, it mean the error is actually the false alarm, but the "connection time out" probably actual error, so I should check if the whatsapp is actually active on my phone

**Comment by muhsatrio** [comment]
Hi @k1m0ch1, actually file .gob wasn't generated after I scanned the QR code. Aah okay, I'll re-try again if the whatsapp has been active again.

**Comment by muhsatrio** [comment]
Ah my bad, actually the .gob file had been generated in `sessions/` folder.

<img width="464" alt="Screen Shot 2021-10-02 at 05 38 42" src="https://user-images.githubusercontent.com/11547086/135693211-e4e2d0eb-a02d-47e9-ae0a-f75e09fca262.png">

I think I can continue to the next step. Okay thank you @k1m0ch1 for the response and guide!
